"""Initial Traveo Schema

Revision ID: 69b06206a342
Revises: 
Create Date: 2026-07-23 22:05:08.067410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b06206a342'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_rides', sa.Integer(), nullable=False),
    sa.Column('completed_rides', sa.Integer(), nullable=False),
    sa.Column('cancelled_rides', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('average_occupancy', sa.Float(), nullable=False),
    sa.Column('average_wait_seconds', sa.Float(), nullable=False),
    sa.Column('active_passengers', sa.Integer(), nullable=False),
    sa.Column('active_drivers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_statistics_date'), 'daily_statistics', ['date'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', 'ADMIN', 'SUPER_ADMIN', 'SUPPORT', 'FINANCE', 'OPERATIONS', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('admin_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('driver_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_locations_driver_id'), 'driver_locations', ['driver_id'], unique=True)
    op.create_table('driver_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=50), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('driver_rating', sa.Float(), nullable=False),
    sa.Column('completed_rides', sa.Integer(), nullable=False),
    sa.Column('cancelled_rides', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EXPIRED', name='verification_status_type'), nullable=False),
    sa.Column('online_status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', name='online_status_type'), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('driver_rating >= 0 AND driver_rating <= 5', name='chk_driver_rating'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_driver_profiles_online_status'), 'driver_profiles', ['online_status'], unique=False)
    op.create_index(op.f('ix_driver_profiles_verification_status'), 'driver_profiles', ['verification_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('RIDE', 'PAYMENT', 'PROMOTION', 'SUPPORT', 'SYSTEM', 'SECURITY', 'WALLET', name='notification_type_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('passenger_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_locations_passenger_id'), 'passenger_locations', ['passenger_id'], unique=False)
    op.create_table('passenger_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender_type'), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('home_location', sa.Text(), nullable=True),
    sa.Column('work_location', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('completed_rides', sa.Integer(), nullable=False),
    sa.Column('cancelled_rides', sa.Integer(), nullable=False),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('average_rating >= 0 AND average_rating <= 5', name='chk_passenger_rating'),
    sa.CheckConstraint('cancelled_rides >= 0', name='chk_passenger_cancelled'),
    sa.CheckConstraint('completed_rides >= 0', name='chk_passenger_completed'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ride_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_status', sa.Enum('FORMING', 'WAITING_FOR_VOTE', 'VOTING', 'FINALIZED', 'SEARCHING_DRIVER', 'DRIVER_ASSIGNED', 'LOCKED', 'CANCELLED', name='group_status_type'), nullable=False),
    sa.Column('maximum_capacity', sa.Integer(), nullable=False),
    sa.Column('current_passengers', sa.Integer(), nullable=False),
    sa.Column('estimated_fare', sa.Float(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('common_otp', sa.String(length=10), nullable=True),
    sa.Column('search_radius', sa.Float(), nullable=True),
    sa.Column('matching_completed', sa.Boolean(), nullable=False),
    sa.Column('group_locked', sa.Boolean(), nullable=False),
    sa.Column('pickup_sequence_generated', sa.Boolean(), nullable=False),
    sa.Column('drop_sequence_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_groups_driver_id'), 'ride_groups', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_groups_group_status'), 'ride_groups', ['group_status'], unique=False)
    op.create_table('ride_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('pickup_latitude', sa.Float(), nullable=False),
    sa.Column('pickup_longitude', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('destination_latitude', sa.Float(), nullable=False),
    sa.Column('destination_longitude', sa.Float(), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=True),
    sa.Column('requested_seats', sa.Integer(), nullable=False),
    sa.Column('ride_type', sa.Enum('SHARED', 'SOLO', 'RENTAL', 'AIRPORT', 'INTERCITY', name='ride_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHING', 'MATCHED', 'CANCELLED', 'EXPIRED', name='ride_request_status_type'), nullable=False),
    sa.Column('estimated_fare', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('requested_seats > 0 AND requested_seats <= 6', name='chk_requested_seats'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ride_requests_status_created', 'ride_requests', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_ride_requests_passenger_id'), 'ride_requests', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_ride_requests_status'), 'ride_requests', ['status'], unique=False)
    op.create_table('saved_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_places_user_id'), 'saved_places', ['user_id'], unique=False)
    op.create_table('system_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configuration_key'), 'system_configuration', ['key'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('balance >= 0', name='chk_wallet_balance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('driver_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_group_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'TIMED_OUT', 'CANCELLED', name='driver_assignment_status_type'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_group_id'], ['ride_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_assignments_driver_id'), 'driver_assignments', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_assignments_ride_group_id'), 'driver_assignments', ['ride_group_id'], unique=False)
    op.create_table('group_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Enum('CONTINUE', 'WAIT', 'CANCEL', name='vote_choice_type'), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ride_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'passenger_id', name='uq_group_vote')
    )
    op.create_index(op.f('ix_group_votes_group_id'), 'group_votes', ['group_id'], unique=False)
    op.create_table('matching_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=False),
    sa.Column('matching_radius', sa.Float(), nullable=False),
    sa.Column('matching_status', sa.String(length=30), nullable=False),
    sa.Column('timer_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timer_expired', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_sessions_ride_request_id'), 'matching_sessions', ['ride_request_id'], unique=False)
    op.create_table('ride_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('ride_request_id', sa.UUID(), nullable=True),
    sa.Column('pickup_order', sa.Integer(), nullable=True),
    sa.Column('drop_order', sa.Integer(), nullable=True),
    sa.Column('boarding_status', sa.Enum('WAITING', 'BOARDED', 'NO_SHOW', 'CANCELLED', name='boarding_status_type'), nullable=False),
    sa.Column('drop_status', sa.Enum('PENDING', 'DROPPED', 'CANCELLED', name='drop_status_type'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ride_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_request_id'], ['ride_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'passenger_id', name='uq_group_passenger')
    )
    op.create_index(op.f('ix_ride_group_members_group_id'), 'ride_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_ride_group_members_passenger_id'), 'ride_group_members', ['passenger_id'], unique=False)
    op.create_table('ride_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_group_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'EMOJI', 'SYSTEM', 'IMAGE', 'LOCATION', name='message_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_group_id'], ['ride_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_messages_ride_group_id'), 'ride_messages', ['ride_group_id'], unique=False)
    op.create_table('ride_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_group_id', sa.UUID(), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ride_group_id'], ['ride_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_otps_ride_group_id'), 'ride_otps', ['ride_group_id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_group_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('ride_status', sa.Enum('REQUEST_CREATED', 'SEARCHING_PASSENGERS', 'GROUP_FORMING', 'WAITING_FOR_VOTE', 'SEARCHING_DRIVER', 'DRIVER_ASSIGNED', 'OTP_GENERATED', 'DRIVER_EN_ROUTE', 'PICKUP_IN_PROGRESS', 'ALL_PASSENGERS_BOARDED', 'RIDE_STARTED', 'DROP_IN_PROGRESS', 'RIDE_COMPLETED', 'PAYMENT_COMPLETED', 'RATING_PENDING', 'RATING_COMPLETED', 'PASSENGER_CANCELLED', 'DRIVER_CANCELLED', 'GROUP_CANCELLED', 'MATCHING_FAILED', 'NO_DRIVER_FOUND', 'PAYMENT_FAILED', 'REFUND_INITIATED', name='ride_status_type'), nullable=False),
    sa.Column('ride_started', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ride_completed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_distance', sa.Float(), nullable=True),
    sa.Column('actual_duration', sa.Float(), nullable=True),
    sa.Column('total_fare', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_group_id'], ['ride_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rides_driver_status', 'rides', ['driver_id', 'ride_status'], unique=False)
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_ride_group_id'), 'rides', ['ride_group_id'], unique=False)
    op.create_index(op.f('ix_rides_ride_status'), 'rides', ['ride_status'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pollution_certificate', sa.String(length=500), nullable=True),
    sa.Column('registration_document', sa.String(length=500), nullable=True),
    sa.Column('vehicle_photo', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='vehicle_status_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('seat_capacity > 0', name='chk_seat_capacity'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_vehicles_driver_id'), 'vehicles', ['driver_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', 'REFUND', 'PROMOTION', 'RIDE_PAYMENT', 'PAYOUT', 'ADJUSTMENT', name='wallet_tx_type'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('driver_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payout_status_type'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_payouts_driver_id'), 'driver_payouts', ['driver_id'], unique=False)
    op.create_table('drop_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('drop_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drop_events_ride_id'), 'drop_events', ['ride_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('UPI', 'CARD', 'WALLET', 'CASH', 'NET_BANKING', name='payment_method_type'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='payment_status_type'), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('payment_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_ride_id'), 'payments', ['ride_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('pickup_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('no_show', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_events_ride_id'), 'pickup_events', ['ride_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('rated_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='chk_rating_range'),
    sa.ForeignKeyConstraint(['rated_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ride_id', 'rater_id', 'rated_id', name='uq_ride_rating')
    )
    op.create_index(op.f('ix_ratings_ride_id'), 'ratings', ['ride_id'], unique=False)
    op.create_table('ride_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('matching_duration_seconds', sa.Float(), nullable=True),
    sa.Column('driver_assignment_seconds', sa.Float(), nullable=True),
    sa.Column('total_pickup_seconds', sa.Float(), nullable=True),
    sa.Column('total_ride_seconds', sa.Float(), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('route_efficiency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_statistics_ride_id'), 'ride_statistics', ['ride_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'WAITING_USER', 'RESOLVED', 'CLOSED', name='support_status_type'), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='refund_status_type'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_ride_statistics_ride_id'), table_name='ride_statistics')
    op.drop_table('ride_statistics')
    op.drop_index(op.f('ix_ratings_ride_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_pickup_events_ride_id'), table_name='pickup_events')
    op.drop_table('pickup_events')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_ride_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_drop_events_ride_id'), table_name='drop_events')
    op.drop_table('drop_events')
    op.drop_index(op.f('ix_driver_payouts_driver_id'), table_name='driver_payouts')
    op.drop_table('driver_payouts')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_vehicles_driver_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_rides_ride_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_ride_group_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_index('idx_rides_driver_status', table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_ride_otps_ride_group_id'), table_name='ride_otps')
    op.drop_table('ride_otps')
    op.drop_index(op.f('ix_ride_messages_ride_group_id'), table_name='ride_messages')
    op.drop_table('ride_messages')
    op.drop_index(op.f('ix_ride_group_members_passenger_id'), table_name='ride_group_members')
    op.drop_index(op.f('ix_ride_group_members_group_id'), table_name='ride_group_members')
    op.drop_table('ride_group_members')
    op.drop_index(op.f('ix_matching_sessions_ride_request_id'), table_name='matching_sessions')
    op.drop_table('matching_sessions')
    op.drop_index(op.f('ix_group_votes_group_id'), table_name='group_votes')
    op.drop_table('group_votes')
    op.drop_index(op.f('ix_driver_assignments_ride_group_id'), table_name='driver_assignments')
    op.drop_index(op.f('ix_driver_assignments_driver_id'), table_name='driver_assignments')
    op.drop_table('driver_assignments')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_system_configuration_key'), table_name='system_configuration')
    op.drop_table('system_configuration')
    op.drop_index(op.f('ix_saved_places_user_id'), table_name='saved_places')
    op.drop_table('saved_places')
    op.drop_index(op.f('ix_ride_requests_status'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_passenger_id'), table_name='ride_requests')
    op.drop_index('idx_ride_requests_status_created', table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_ride_groups_group_status'), table_name='ride_groups')
    op.drop_index(op.f('ix_ride_groups_driver_id'), table_name='ride_groups')
    op.drop_table('ride_groups')
    op.drop_table('passenger_profiles')
    op.drop_index(op.f('ix_passenger_locations_passenger_id'), table_name='passenger_locations')
    op.drop_table('passenger_locations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('idx_notifications_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_driver_profiles_verification_status'), table_name='driver_profiles')
    op.drop_index(op.f('ix_driver_profiles_online_status'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_driver_locations_driver_id'), table_name='driver_locations')
    op.drop_table('driver_locations')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_daily_statistics_date'), table_name='daily_statistics')
    op.drop_table('daily_statistics')
    # ### end Alembic commands ###
